services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqlvol:/var/lib/mysql
      - ./backup:/var/backup
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - '${MYSQL_PORT}:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD

  redis:
    image: redis
    volumes:
      - redisvol:/data
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASS}
      - |
        redis-server --daemonize yes
    ports:
      - '${REDIS_PORT}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

volumes:
  mysqlvol:
  redisvol:
